### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by SolarBear**
Done with the translation!

I still need to have a good, hard look at the site and I will certainly reword some stuff but these should only be minor changes.

### CODE REVIEW

**Comment by stevenvergenz** [comment]
Beautiful! I guess you didn't see my reddit PM about how the terms, privacy policy, and howto sections were optional?

**Comment by SolarBear** [comment]
Meh. I'd rather get the whole thing done. :smile:

**Comment by stevenvergenz** [comment]
Looks like there are still a couple strings that need translation, and a couple duplicates. I found howto.notes.f1, skills.p1.f1, user.notoons.p2.f1, and killtoon.intro with duplicates, and about.meta_description, nav.flexbox_unsupported, and login.clientStrings untranslated. There might be more, so I'd appreciate a quick read-through before I push this to production.

**Comment by stevenvergenz** [comment]
And once again, your latest translation is live at the dev server: http://toonstore.net:3000/

**Comment by SolarBear** [comment]
Certainly! I finished quite late yesterday so I didn't do a thorough review, I'll finish during lunch time.

**Pull request merged**
